CREATE DATABASE PROJETO_ADMINISTRADOR_DE_LEITURAS;

USE PROJETO_ADMINISTRADOR_DE_LEITURAS;

CREATE TABLE ADMINISTRADOR_DE_LEITURAS (
	NOME_DO_LIVRO varchar(200) ,
	AUTOR varchar(100) ,
	SINOPSE text,
	TOTAL_DE_PAGINAS int, 
	PAGINAS_LIDAS int, 
	STATUS_DE_LEITURA varchar(50), 
	DATA_DE_INICIO date, 
	DATA_DE_CONCLUSAO date
);